### PR TITLE
Fixed #176 AmbiguousMatchException when deleting package

### LINKED ISSUE #176: AmbiguousMatchException when deleting package
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

1. Publish a package.
2. Attempt to delete, something like `dotnet nuget delete -s http://localhost:50557 test-package 0.0.0`.

### What did you expect to see?

Deleted package.

### What did you see instead?

Console output:

```
warn : Deleting test-package 0.0.0 from the 'http://localhost:50557'.
info :   DELETE http://localhost:50557/api/v2/package/test-package/0.0.0
info :   InternalServerError http://localhost:50557/api/v2/package/test-package/0.0.0 143ms
info :   DELETE http://localhost:50557/api/v2/package/test-package/0.0.0
info :   InternalServerError http://localhost:50557/api/v2/package/test-package/0.0.0 13ms
info :   DELETE http://localhost:50557/api/v2/package/test-package/0.0.0
info :   InternalServerError http://localhost:50557/api/v2/package/test-package/0.0.0 8ms
error: Response status code does not indicate success: 500 (Internal Server Error).
```

Got this in server output:

```
BaGet.Controllers.PackagePublishController.Delete (BaGet)
BaGet.Controllers.PackagePublishController.Relist (BaGet)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(CandidateSet candidates)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, EndpointSelectorContext context, CandidateSet candidateSet)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.SelectAsync(HttpContext httpContext, EndpointSelectorContext context, CandidateSet candidateSet)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.MatchAsync(HttpContext httpContext, EndpointSelectorContext context)
   at Microsoft.AspNetCore.Routing.Matching.DataSourceDependentMatcher.MatchAsync(HttpContext httpContext, EndpointSelectorContext context)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Output of `git rev-parse HEAD`: (_What version of BaGet are you using?_)

```
c38a4bdb599356f60ec773e44609e4e98a779b02
```

### PR DESCRIPTION
**Pull request by Mizipzor**
### What does this PR do?

Fix bug.

### Closes Issue(s)

#176 

### Motivation

Need it.

### CODE REVIEW

File: src/BaGet/Controllers/PackagePublishController.cs [hunk 1]
```diff
@@ -77,6 +76,7 @@ public async Task Upload(CancellationToken cancellationToken)
             }
         }
 
+        [HttpDelete]
```
Comment (loic-sharma) [inline src/BaGet/Controllers/PackagePublishController.cs]: Weird. This worked in 2.1 by adding constraints like `HttpMethodRouteConstraint("POST")`. I wonder if registering the route with `MapPost` and `MapDelete` [here](https://github.com/loic-sharma/BaGet/blob/master/src/BaGet/Extensions/IRouteBuilderExtensions.cs#L25) would fix this issue.

Comment (loic-sharma) [reply src/BaGet/Controllers/PackagePublishController.cs]: `MapPost` and `MapDelete` don't accept a name, which would break the URL generation. So that'd be more work to fix

**Comment by loic-sharma** [comment]
Good find! Thanks for fixing this :)
